# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-backend
  template:
    metadata:
      labels:
        app: backstage-backend
    spec:
      containers:
        - name: backstage-backend
          image: backstage-backend:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 7007
          readinessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-backend-service
  namespace: backstage
spec:
  selector:
    app: backstage-backend
  ports:
    - port: 7007
      targetPort: 7007
  type: NodePort